spring.application.name=Session12_Bai2
# Root log level
logging.level.root=WARN

# Log level cho controller
logging.level.com.example.coursemanagement.controller=INFO

# Log level cho service
logging.level.com.example.coursemanagement.service=INFO

# Pattern console
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n